version: 2
updates:
- package-ecosystem: composer
  directory: "/server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: npm
  directory: "/server/resources"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
