pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - check-success~=Testing
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge
