pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - check-success~=PHP
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge
