image:
  file: .gitpod.dockerfile
ports:
  - port: 8001
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
tasks:
  - name: Apache
    command: >
        mkdir /tmp/apache;
        touch /tmp/apache/error.log;
        touch /tmp/apache/access.log;
        export APACHE_PID_FILE="/tmp/apache/PID" APACHE_RUN_USER="gitpod" APACHE_RUN_GROUP="gitpod" APACHE_SERVER_NAME="localhost" APACHE_LOG_DIR="/tmp/apache";
        apache2;
        multitail /tmp/apache/error.log -I /tmp/apache/access.log;
  - name: Allerta
    init: >
        cd server;
        composer install;
        composer update;
        cd resources;
        npm install;
        npm run prod;
        cd ../..;
    command: >
        cd server/install;
        WORKSPACE_URL=$(gp url 8001 | sed -E s/\\/$//);
        mysql -e "CREATE DATABASE IF NOT EXISTS allerta";
        mysql -e "CREATE USER 'allerta'@'localhost' IDENTIFIED BY 'allerta_pwd';";
        mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'allerta'@'localhost';";
        mysqladmin reload;
        php install.php config -n "allerta" -u "allerta" -a "allerta_pwd" -o $WORKSPACE_URL -r "DEV_ENV";
        php install.php populate -m "admin" -b -d -s "password" -w "owner" -e "mail@mailserver.local";
        cd ..;
        wget https://github.com/vrana/adminer/releases/download/v4.8.0/adminer-4.8.0.php;
        mv adminer-4.8.0.php adminer.php
vscode:
  extensions:
    - gruntfuggly.todo-tree@0.0.205:sbsZJOTJzKZtMVHQuS2iPw==
    - coenraads.bracket-pair-colorizer-2@0.1.4:+JUeb/jFYZt2/0MS/gUllA==
    - shelex.vscode-cy-helper@1.1.0:U9ok2y1bSmqn17OMuRMOfw==
    - hookyqr.beautify@1.4.11:n9DJEUFbYD/YHaBXxm+pYw==