#Inspired from

image:
  file: .gitpod.dockerfile
ports:
  - port: 8001
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
tasks:
  - name: Apache
    command: >
        touch /var/log/apache2/error.log;
        touch /var/log/apache2/access.log;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log
  - name: Allerta
    init: >
        cd server;
        composer install;
        composer update;
        cd resources;
        npm install;
        npm run prod;
        cd ../..;
    command: >
        cd server/install;
        WORKSPACE_URL=$(gp url 8001 | sed -E s/\\/$//);
        mysql -e "CREATE DATABASE IF NOT EXISTS allerta";
        mysql -e "CREATE USER 'allerta'@'localhost' IDENTIFIED BY 'allerta_pwd';";
        mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'allerta'@'localhost';";
        mysqladmin reload;
        php install.php config -n "allerta" -u "allerta" -a "allerta_pwd" -o "127.0.0.1" -r "DEV_ENV";
        php install.php populate -m "admin" -b -s "password" -w "owner" -e "mail@mailserver.local";
        apachectl start;