name: PHP Code Testing

on:
  push:
  pull_request:

jobs:
  tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    defaults:
      run:
        working-directory: ./server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl
        ini-values: post_max_size=256M, short_open_tag=On
        coverage: xdebug, pcov

    - name: Start webserver
      run: |
        nohup php -S 0.0.0.0:8080 &
        sleep 5 && curl 127.0.0.1:8080/.htaccess # request a simple static file

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: WebPack Setup
      run: |
        cd resources
        npm install
        webpack --mode=production

    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop

    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: 'password'
        mysql user: 'user'
        mysql password: 'password'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress
        npm init --yes
        npm install --save-dev cypress

    - name: Mysql test
      run: mysql -u root -h "127.0.0.1" -ppassword -e "SHOW DATABASES;"

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        record: true
        working-directory: server
        tag: php-${{ matrix.php-versions }}
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress_screenshots_php-${{ matrix.php-versions }}
        path: cypress/screenshots

