name: PHP Code Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      working-directory: ./server

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Start MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          mysql root password: ''
          mysql database: allerta
          mysql user: user
          mysql password: password

      - name: Validate composer.json and composer.lock
        run: composer validate
        working-directory: ${{env.working-directory}}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        working-directory: ${{env.working-directory}}

      - name: Run test suite
        run: composer run-script test
        working-directory: ${{env.working-directory}}
